version: '3.7'

networks:
  app:
    driver: bridge
  db:
    external:
      name: mariadb_app
  backend:
    external:
      name: global_app

services:
  workspace:
    build:
      context: ./workspace
    image: ${COMPOSE_PROJECT_NAME}_workspace:latest
    volumes:
      - ../:/var/htdocs
    tty: true
    networks:
      - app
      - backend
      - db

  nginx:
    build:
      context: ./nginx
    image: ${COMPOSE_PROJECT_NAME}_nginx:latest
    volumes:
      - ../public:/var/htdocs/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - db
      - app
    ports:
      - "80:80"
      - "443:443"

  php-fpm:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
    image: ${COMPOSE_PROJECT_NAME}_php-fpm:latest
    volumes:
      - ../:/var/htdocs
    networks:
      - db
      - app

  php-cli:
    build:
      context: ./php-cli
      args:
        - PHP_VERSION=${PHP_VERSION}
    image: ${COMPOSE_PROJECT_NAME}_php-cli:latest
    volumes:
      - ../:/var/htdocs
    networks:
      - db
      - app